### ISSUE TITLE
Apostrophe in HTML must be encoded with '&#39;' instead of '&apos;'

### ISSUE THREAD

**Issue by ohardy** [fb55/entities#20]
CF http://www.w3.org/TR/xhtml1/#C_16

**Comment by sberryman** [comment]
This is still and issue and I've finally figured out this package is the culprit.

**Comment by ggentzke** [comment]
Requires update to `entities.json` to capture `&#39;` on decode and a hook to always choose `&#39;` when encoding `'`.  @sberryman the power is in your hands :)

**Comment by sberryman** [comment]
Yeah, I finally figured it out... Guess I should have posted my findings here.

**Comment by sterlinghw** [comment]
+1

**Comment by psolbach** [comment]
This is still an issue. For a lib that's required by cheerio I find this a bit disconcerting. Scenario here: Corporate email that contains stuff parsed by cheerio, &apos; renders as plaintext in Outlook environment. This is not valid HTML. What should we do about it? Fork and ping cheerio maintainers?

**Comment by fb55** [comment]
For cheerio's case, I would like to solve this by implementing https://github.com/cheeriojs/cheerio/issues/863. This module could use a new API as well, which differentiates between encoding and escaping (with the latter only encoding characters that are illegal in HTML).

**Comment by lahiru-tennakoon** [comment]
Seems like this is still an issue.. Any particular reason why it has not been fixed yet?
Is there still no way to encode apostrophe to the html code (&#39)?

**Comment by fb55** [comment]
You probably want to use the `escape` methods if this is an issue for you.

**Comment by chapmanio** [comment]
Why was this closed?  I can't see that it has been "completed" and the `escape` methods don't work either.  Does anyone have any examples to share of achieving this with the in-built methods?

**Comment by fb55** [comment]
Why don't the escape methods work?
