### ISSUE TITLE
entities 2.0.2 includes es6 regular expression flag/u

### ISSUE THREAD

**Issue by farmerx** [fb55/entities#209]
entities 2.0.2 includes es6 regular expression flag /u

**Comment by farmerx** [comment]
https://github.com/fb55/entities/blob/931146637302d8fcdbc42180c2cd37d078f59dd5/src/encode.ts#L65

**Comment by syabro** [comment]
+1 here

It breaks IE. But since ts target is set to `es5` maybe it's ts bug and it should be transformed somehow?

**Comment by mmaameriacap** [comment]
Same problem

**Comment by lehongson12** [comment]
Same problem, It breaks IE

**Comment by syabro** [comment]
I think it could ve replaced `new` call.
```ts
const reNonASCII = new RegExp("[^\\0-\\x7F]", "gu"); 
```

**Comment by melnikaite** [comment]
No, in IE11 it still shows `Syntax error in regular expression` because of `u` modifier

**Comment by Nabsef** [comment]
Same issue.

**Comment by Nabsef** [comment]
> +1 here
> 
> It breaks IE. But since ts target is set to `es5` maybe it's ts bug and it should be transformed somehow?

Same issue.

**Comment by venoral** [comment]
`node v4.4.2
npm v2.15.0
/tmp/build/src/node_modules/html-webpack-plugin/node_modules/pretty-error/node_modules/renderkid/node_modules/css-select/node_modules/domutils/node_modules/dom-serializer/node_modules/entities/lib/encode.js:54
var reNonASCII = /[^\0-\x7F]/gu;
^
SyntaxError: Invalid flags supplied to RegExp constructor 'gu'`

**Comment by manish-kothari** [comment]
I changed the regex to a version compatible with ES5 using regexpu:

`const reNonASCII = /[^\0-\x7F]/gu;
const reNonASCII = /(?:[\x80-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])/g;`

Perhaps this can help.
I have also raised pull request for this, hope this gets merged.

**Comment by Nabsef** [comment]
Hello, I have just started npm insall for my package, I still have the old version "entities@2.0.2" :
```
+-- domutils@1.7.0 
| | | `-- dom-serializer@0.2.2 
| | |   +-- domelementtype@2.0.1 
| | |   `-- entities@2.0.2 

```
I think we have update or merge issue for the new version.

**Comment by melnikaite** [comment]
It's not yet merged to master, there are 2 PRs to fix this #212 and #208 
As a workaround you can add to package.json version 2.0.0

**Comment by mmaameriacap** [comment]
> It's not yet merged to master, there are 2 PRs to fix this #212 and #208
> As a workaround you can add to package.json version 2.0.0

Actually, in my side , I cannot use the version 2.0.0 because the problems is related to a dependency of dependency of dependency... So at the end , we don't have the control of the exact version to use. We can complete review the solution but I think it will be ridiculous to do it just regarding the change made in the entities. We are waiting the fix to be able to continue our development which are stopped since the change made.
The npm version using in our solution is very old and the option npm ci is not available yet...So thanks in advance for your work

**Comment by melnikaite** [comment]
You can try to install your own fork with working version using git url `npm install mmaameriacap/entities`
Probably `npm` will dedupe it and use for dependencies of dependencies

**Comment by JonShort** [comment]
Hi all - a workaround for others which are having issues with this being a sub-dependency is to manually edit your lockfile, replacing any entities 2.0.2 with 2.0.0:

Then just make sure your CI is using `npm ci` or `yarn install --frozen-lockfile` respectively.

**npm:**
```json
"entities": {
    "version": "2.0.0",
    "resolved": "https://registry.npmjs.org/entities/-/entities-2.0.0.tgz",
    "integrity": "sha512-D9f7V0JSRwIxlRI2mjMqufDrRDnx8p+eEOz7aUM9SuvF8gsBzra0/6tbjl1m8eQHrZlYj6PxqE00hZ1SAIKPLw=="
}
```

**yarn:**
```yml
entities@2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/entities/-/entities-2.0.0.tgz#68d6084cab1b079767540d80e56a39b423e4abf4"
  integrity sha512-D9f7V0JSRwIxlRI2mjMqufDrRDnx8p+eEOz7aUM9SuvF8gsBzra0/6tbjl1m8eQHrZlYj6PxqE00hZ1SAIKPLw==
```

**Comment by shobhitchittora** [comment]
Hi all!
When can we release a patch version with the backward compat fixes? Any updates on this?
