### ISSUE TITLE
&#xA0; is decoded as a problematic non-breaking space

### ISSUE THREAD

**Issue by ggentzke** [fb55/entities#22]
When the html entity `&#xA0;` is decoded via `entities.decodeHTML(myHtml);`, it results in a strange non-breaking space that is detected by some IDEs such as Sublime as non-standard.  This detection actually helped me find the following unintended bug: 

When using a markdown interpreter, md notation that immediate follows this special character is left unevaluated, and thus you'll end up with content such as ` _Liar's Poker_` in the output instead of _Liar's Poker_.

Example of Sublime calling out the character:
<img width="362" alt="screen shot 2015-07-07 at 5 23 22 pm" src="https://cloud.githubusercontent.com/assets/14310/8557677/ed2f0d62-24cc-11e5-8907-c2955b866e9a.png">

**Comment by ggentzke** [comment]
After looking through the maps and tests, I see you aren't addressing this entity at all.  I also understand this is something related to the particular markdown interpreter (notably  _Liar's Poker_ works in GFM).
 If this is interesting to you I can submit a PR.

**Comment by fb55** [comment]
Is there any web standard that requires the entity to be mapped to another value, or is your problem only that it isn't supported by an application?
