### ISSUE TITLE
More efficient entities encoding

### ISSUE THREAD

**Issue by fabiospampinato** [fb55/entities#304]
The JSON entities map this library uses can be minified further, currently entities are stored using unicode escape sequences, which for example for `\u00C1` means we have to store 6 characters on disk, while in practice we could just store `Á`, 1 character.

With this optimization performed on all entities the size of the uncompressed JSON map goes from 44.8kb to 32.9kb, the size of the map when zipped goes down from 12.3kb to 11.9kb.

IMO this optimization is strictly an improvement with no downsides. The zipped size change doesn't seem that significant but the map still needs to be decompressed before being used, and the removed 12kb are 12 less kilobytes that need to be parsed. Plus in some applications, like Electron apps, your code isn't really being served in a compressed form either so that's 12 more kilobytes to read from disk.

Should I submit a PR for it?

**Comment by fb55** [comment]
Turns out Node [uses `utf8`](https://github.com/nodejs/node/blob/2cfdf28413fd9a7bfab65cb49cff6e50ab0c21ec/lib/internal/modules/cjs/loader.js#L1107) when loading JSON files. Happy to accept PRs for this!
