### ISSUE TITLE
TypeError: Cannot read property 'decodeHTML' of undefined

### ISSUE THREAD

**Issue by orzhtml** [fb55/entities#55]
TypeError: Cannot read property 'decodeHTML' of undefined

entities: '2.0.0'

**Comment by fb55** [comment]
Could you provide a code sample to reproduce this?

**Comment by orzhtml** [comment]
`import entities from 'entities'`
`entities.decodeHTML("asdf &amp; &yuml; &uuml; &apos;");`

TypeError: Cannot read property 'decodeHTML' of undefined

**Comment by orzhtml** [comment]
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
      Memory: 566.99 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.1
        System Images: android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      eslint-plugin-react-native: 3.5.0
      react-native-cli: 2.0.1

**Comment by Yang-Andy** [comment]
I found a fix for this. 
Use this line ```const entities = require("entities");```  instead of 
```import entities from 'entities'```.
 Or you could do something like this too ```import { decodeHTML } from 'entities';```

**Comment by fb55** [comment]
This should probably be `import * as entities from ‘entities’`
