### ISSUE TITLE
Question: Bundle size v3+

### ISSUE THREAD

**Issue by RaphaelWoude** [fb55/entities#587]
I just migrated an application from `he` to `entities` but the bundle size for v3 is much bigger than v2. Is there a reason for this?

![image](https://user-images.githubusercontent.com/47354694/131644336-fdeb1040-7cfb-4588-80a0-57a9af3fa08d.png)
![image](https://user-images.githubusercontent.com/47354694/131644237-d6f4e6dc-3076-47c7-a138-46ce9bf0d7ed.png)

**Comment by fb55** [comment]
Encoding and decoding no longer share the same data structure. This leads to a big speed-up, and if you only either encode or decode, your bundler will remove the other path.
