### ISSUE TITLE
Add `entities.json` to exports

### ISSUE THREAD

**Issue by puzrin** [fb55/entities#783]
**Problem**

We use this package as raw data source for many years https://github.com/markdown-it/markdown-it/blob/master/lib/common/entities.js#L6. Since v4 new format of `package.json` exports only explicitely listed entries, and `entities.json` is not accessible anymore.

**Suggestion**

Consider add `entities.json` to exports.

**Comment by fb55** [comment]
Hi @puzrin, the `entities.json` file is unfortunately no longer a part of the files shipped to NPM. Instead, we now use a trie that was serialized as a `Uint16Array`; [details here](https://github.com/fb55/entities/blob/master/scripts/trie/README.md).

For markdown-it, you might want to adopt the [decoding logic](https://github.com/fb55/entities/blob/40c22fe6706f1dcdf8270a63a07ea4958fd2169d/src/decode.ts#L76-L128) of the trie. This is already done [in htmlparser2](https://github.com/fb55/htmlparser2/blob/7a1971fc3d40f1f416126502ccff8ca03943e367/src/Tokenizer.ts#L639-L725).

**Comment by puzrin** [comment]
May be you could consider to ship `list()` method as part of this package?

I mean, current API provides `encode` + `decode`. IMO `encode` + `decode` + `list` (index?) would be consistent and more flexible.

**Comment by fb55** [comment]
What is the return value you'd expect from `list`?

**Comment by fb55** [comment]
This mapping isn't easy to compute anymore (but not impossible). On the other hand, `markdown-it` might benefit from embracing the new approach:

The reason the format of entities was changed is that in HTML, many entities have an optional semicolon. Eg. `&amp` is equivalent to `&amp;`. The trie is used to match these as well, at a great speed. `markdown-it` would gain in correctness by embracing this.

Let me know if this is something you'd be interested in — I'm happy to help.

**Comment by fb55** [comment]
> moving `entities.json` to outer standalone package

This already exists as eg. https://github.com/wooorm/character-entities 🙂

**Comment by puzrin** [comment]
> This already exists as eg. https://github.com/wooorm/character-entities :slightly_smiling_face:

We started use `entities` before that package existed :). Another problem - referred package is ESM only.

Using entities v3 is acceptable too. Let's close issue, because i don't wish to insist on anything about your package. If you find some of my thoughts useful - feel free to use as you wish. If nothing interesting - no problem. Anyway, thanks for your work.

**Comment by fb55** [comment]
> Using entities v3 is acceptable too

👍 That makes a lot of sense as well. HTML entities most likely will never be added, so there is no reason really to update.
